name: RUN puppeteer

on:
  pull_request:
    branches:
      - develop
      - release
      - main
  push:
    branches:
      - develop
      - release
      - main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [16.14.2]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.14.2
        uses: actions/setup-node@v1
        with:
          node-version: '16.14.2'
      - name: install command
        run: yarn install

      - name: RUN test e2e
        run: yarn test:e2e
